export const staffMasterItems = {
    fax_mo: "",
    is_foreigner:'',
    gentle: "0",
    remark: "",
    skills: null,
    tel_no: "01234567892",
    userid: "5651561",
    address: "千葉県千葉市美浜区4-1打瀬",
    cell_no: "21111111",
    pc_mail: "",
    tel_no1: "11",
    tel_no2: "11",
    tel_no3: "66",
    birthday: "2023-07-06",
    cell_no1: "080",
    cell_no2: "2222",
    cell_no3: "33333",
    etc_mail: null,
    mynumber: "11",
    staff_id: "sysadmin",
    tenpo_cd: null,
    bank_code: "0005",
    bank_kana: "",
    bank_name: "三菱ＵＦＪ",
    car_color: "",
    car_model: "",
    dep_array: [
    {
        id: 1,
        dependent_name: "wwww",
        dependent_gender: "1",
        dependent_tax_flg: "0",
        dependent_birthday: "2024-04-11",
        dependent_business: "wwwww",
        dependent_address_1: "千葉県",
        dependent_address_2: "千葉市",
        dependent_address_4: "q",
        dependent_name_kana: "haiting chen kk janga tech",
        dependent_post_code: "261-0023",
        dependent_address_kana: "www",
        dependent_relationship: "夫"
    }
    ],
    kana_name: "ﾁﾊﾞﾀﾛ",
    mail_date: null,
    mail_flag: "1",
    post_code: "2610013",
    self_type: null,
    work_type: "1",
    bank_code2: "",
    bank_kana2: "",
    bank_name2: "",
    blood_type: "3",
    car_number: "",
    company_id: "1234567890",
    created_by: "sysadmin",
    mail_title: null,
    owner_type: null,
    phone_mail: "asanoryou.janga@gmail.com",
    qualified1: "",
    qualified2: "",
    rehide_flg: "0",
    speciality: "",
    staff_m_id: "5651561",
    staff_name: "千葉太郎",
    tenpo_name: null,
    tenpo_type: null,
    updated_by: "sysadmin",
    branch_code: "156",
    branch_kana: "",
    branch_name: "阿佐ヶ谷",
    create_date: "2020-07-15T10:39:25",
    month_money: null,
    paper_print: "0",
    route_array: [
    {
        id: 1,
        type: "mono"
    },
    {
        id: "[object Object]1"
    }
    ],
    school_code: "3333",
    spouse_flag: "0",
    staff_flag1: "3",
    staff_flag2: "1",
    staff_flag3: "0",
    staff_flag4: "0",
    staff_flag5: "0",
    staff_flag6: "1",
    staff_flag7: "0",
    staff_flag8: "0",
    staff_flag9: "0",
    traffic_fee: null,
    update_date: "2022-01-07T11:49:33",
    approval_flg: "2",
    bank_account: "9999999",
    branch_code2: "",
    branch_kana2: "",
    branch_name2: "",
    commuting_by: "5",
    emergency_no: "11123",
    exchange_day: "2021-03-30",
    health_array: [
    {
        file_id: 0,
        file_id2: 0,
        imageRef: {},
        imageRef2: {}
    }
    ],
    mail_address: null,
    mail_content: null,
    married_flag: "1",
    staff_flag10: "0",
    staff_number: 156514651561,
    attached_flag: null,
    bank_account2: "",
    department_id: "3311300",
    disabled_info: null,
    handbook_date: null,
    member_number: "",
    resume_remark: null,
    department_id2: null,
    emergency_name: "太田　大生",
    household_name: "千葉太郎",
    id_change_date: null,
    induction_date: "2021-03-24",
    license_expire: "",
    medical_name_1: "",
    medical_name_2: "",
    training_array: [
    {
        file_id: 0,
        imageRef: {}
    }
    ],
    emp_change_date: null,
    experience_year: "0",
    initiation_date: null,
    official_duties: "1000",
    simplified_name: "XXX",
    spouse_name_flg: "1",
    bank_pay_amount1: "",
    bank_pay_amount2: "",
    car_manufacturer: "",
    current_address1: "千葉県千葉市中央区",
    current_address2: "出洲港",
    dispatch_company: "",
    experience_month: "0",
    nearist_station1: "",
    nearist_station2: null,
    nearist_station3: null,
    resignation_date: "2021-05-04",
    bank_account_kana: "ﾁﾊﾞﾀ",
    bank_account_name: "ｶﾅｶﾅ",
    bank_account_type: "2",
    emergency_tel_no1: "090",
    emergency_tel_no2: "99999",
    emergency_tel_no3: "88888",
    exchange_day_next: null,
    insurance_company: "",
    bank_account_name2: "",
    bank_account_type2: "1",
    car_license_number: "",
    current_post_code1: "260",
    current_post_code2: "0023",
    department_id_next: "",
    emergency_address1: "千葉県千葉市中央区",
    emergency_address2: "出洲港",
    emergency_relation: "叔父",
    kana_name_register: "ﾁﾊﾞ ﾀﾛ",
    residence_address1: "千葉県千葉市中央区",
    residence_address2: "出洲港",
    csv_department_name: null,
    graduated_yearmonth: null,
    qualification_array: [
    {
        file_id: 0,
        file_id2: 0,
        imageRef: null,
        imageRef2: null
    }
    ],
    staff_name_register: "千葉太郎",
    contract_expiry_date: "",
    emergency_post_code1: "260",
    emergency_post_code2: "0023",
    residence_post_code1: "260",
    residence_post_code2: "0023",
    current_address1_kana: "ﾁﾊﾞｹﾝﾁﾊﾞｼﾁｭｳｵｳｸ",
    current_address2_kana: "ﾃﾞｽﾞﾐﾅﾄ",
    last_graduated_school: "",
    medical_checkup_day_1: null,
    medical_checkup_day_2: null,
    employment_category_id: "30",
    household_relationship: "本人",
    insurance_policy_number: "",
    residence_address1_kana: "ﾁﾊﾞｹﾝﾁﾊﾞｼﾁｭｳｵｳｸ",
    residence_address2_kana: "ﾃﾞｽﾞﾐﾅﾄ",
    liability_coverage_amount: "",
    passenger_coverage_amount: "",
    property_damage_coverage_amount: ""
};
